# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-26 18:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('preview', models.TextField()),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DesignProfessional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_prof', models.CharField(max_length=200)),
                ('detail_specification', models.TextField()),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designprofessional', to='i_remote.Design')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_student', models.CharField(max_length=200)),
                ('preview_student', models.TextField()),
                ('publish_date_student', models.DateTimeField(blank=True, null=True)),
                ('author_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
