# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-27 00:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('i_remote', '0004_remotedesigntwo'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteInstallation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('preview', models.TextField()),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RemoteInstallationTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_install', models.CharField(max_length=200)),
                ('detail_specification', models.TextField()),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('install', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remoteinstallation', to='i_remote.RemoteInstallation')),
            ],
        ),
    ]
