# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-27 16:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('i_remote', '0006_designselfcomputer_designselfcomputertwo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormUse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('software', models.CharField(choices=[('ACAD', 'AutoCAD'), ('INVENTOR', 'Autodesk inventor'), ('MEP', 'Revit MEP'), ('ARCHITECTURE', 'Revit  Architecture'), ('STRUCTURE', 'Revit Structure'), ('MAX', '3ds Max')], max_length=3)),
                ('training_duration_in_weeks', models.CharField(max_length=2)),
                ('number_of_trainee', models.CharField(max_length=2)),
                ('school_name', models.CharField(max_length=200)),
                ('design_detail_and_specification', models.CharField(choices=[('CALL', 'Calls'), ('EMAIL', 'Emails'), ('SKYPE', 'Skype Calls'), ('CHAT', 'Chats'), ('VIEWER', 'Team Viewer')], max_length=3)),
                ('license_type', models.CharField(choices=[('NON TRY', 'Licensed'), ('TRY', 'Trial')], max_length=3)),
                ('prefered_output', models.CharField(choices=[('NATIVE', 'Native File'), ('DWF', 'DWF Format'), ('PDF', 'PDF Format')], max_length=3)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
