# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-27 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('i_remote', '0007_formuse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formuse',
            name='publish_date',
        ),
        migrations.AddField(
            model_name='formuse',
            name='approved_form',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='formuse',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
