# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-29 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('i_remote', '0008_auto_20170427_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='formuse',
            name='installation_type',
            field=models.CharField(choices=[('ALONE', 'Stand Alone Installation'), ('NETWORK', 'Network Installation')], default='plo', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formuse',
            name='system_requirement',
            field=models.CharField(choices=[('YES', 'Yes up to system requirement'), ('NO', 'No need to be upgraded'), ('NONO', 'No I want to use it like that')], default='', max_length=3),
            preserve_default=False,
        ),
    ]
