# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-29 12:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('i_remote', '0009_auto_20170429_0811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formuse',
            old_name='design_detail_and_specification',
            new_name='detail_and_specification',
        ),
    ]
