# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-01 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('i_remote', '0010_auto_20170429_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formuse',
            name='company',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='formuse',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='formuse',
            name='first_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='formuse',
            name='last_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='formuse',
            name='software',
            field=models.CharField(choices=[('ACAD', 'AutoCAD'), ('INVENTOR', 'Autodesk inventor'), ('MEP', 'Revit MEP'), ('ARCHITECTURE', 'Revit  Architecture'), ('STRUCTURE', 'Revit Structure'), ('MAX', '3ds Max')], max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='formuse',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
